### ISSUE TITLE
配置项中webhook_secret的问题

### ISSUE THREAD

**Issue by LYF511** [nonebot/adapter-github#2]
在配置此项目时，我 Github App 和 驱动器配置 都没有配置 webhook_secret，因为这是可选项，但我遇到了报错:
```
12-04 14:52:08 [WARNING] nonebot | GitHub | Received invalid GitHub Webhook request. Missing Header.
12-04 14:52:08 [INFO] uvicorn | 140.xx.115.121:32999:0 - "POST /github/webhooks/2xxx91 HTTP/1.1" 400
```
查找源代码后发现[这个文件](https://github.com/nonebot/adapter-github/blob/master/nonebot/adapters/github/adapter.py)中的 Line 75-81 为报错的相关代码。
```
        event_id = request.headers.get("x-github-delivery")
        event_name = request.headers.get("x-github-event")
        signature = request.headers.get("x-hub-signature-256")
        payload = request.content

        if not event_id or not event_name or not signature or not payload:
            log("WARNING", "Received invalid GitHub Webhook request. Missing Header.")
            return Response(400, content="Invalid Request")
```
查看 Webhook 日志时发现缺少 `x-hub-signature-256` 头，但是根据 [Github Docs](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#delivery-headers) 里 `X-Hub-Signature-256` 为必须有 `secret` 才有此项
我添加了 `secret` 正常运行
请问是不是文档的错误，或者代码的缺陷？

**Comment by yanyongyu** [comment]
确实有点问题 等会儿改一下
